---
# Elasticsearch Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: chattingo
  labels:
    app: elasticsearch
    tier: logging
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
    tier: logging
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP

---
# Elasticsearch Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: chattingo
  labels:
    app: elasticsearch
    tier: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      tier: logging
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: logging
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: increase-vm-max-map
        image: busybox:1.35
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox:1.35
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        # Disable security for development
        - name: xpack.security.enabled
          value: "false"
        - name: cluster.name
          value: "chattingo-logs"
        - name: node.name
          value: "chattingo-es-node"
        - name: network.host
          value: "0.0.0.0"
        - name: http.port
          value: "9200"
        - name: bootstrap.memory_lock
          value: "false"
        # Index management
        - name: action.auto_create_index
          value: "chattingo-*"
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: "true"
        - name: cluster.routing.allocation.disk.watermark.low
          value: "85%"
        - name: cluster.routing.allocation.disk.watermark.high
          value: "90%"
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: chattingo-logs
          mountPath: /usr/share/elasticsearch/logs
          subPath: elasticsearch
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data-pvc
      - name: chattingo-logs
        persistentVolumeClaim:
          claimName: chattingo-logs-pvc

---
# Elasticsearch Headless Service for StatefulSet (if needed later)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: chattingo
  labels:
    app: elasticsearch
    tier: logging
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    tier: logging
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
