apiVersion: apps/v1
kind: Deployment
metadata:
  name: chattingo-backend
  namespace: chattingo
spec:
  replicas: 2  # Scale for production
  template:
    spec:
      containers:
      - name: chattingo-backend
        image: adityagaikwad888/chattingo-backend:v1.0.0
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: JAVA_OPTS
          value: "-Xmx1536m -Xms512m -XX:+UseG1GC -XX:MaxRAMPercentage=75.0"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chattingo-frontend
  namespace: chattingo
spec:
  replicas: 2  # Scale for production
  template:
    spec:
      containers:
      - name: chattingo-frontend
        image: adityagaikwad888/chattingo-frontend:v1.0.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: chattingo
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: MYSQL_INNODB_BUFFER_POOL_SIZE
          value: "1G"
        - name: MYSQL_MAX_CONNECTIONS
          value: "200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: chattingo
spec:
  template:
    spec:
      containers:
      - name: elasticsearch
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: ES_JAVA_OPTS
          value: "-Xmx2g -Xms1g"
        - name: cluster.initial_master_nodes
          value: "elasticsearch-0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: chattingo
spec:
  template:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: chattingo-monitoring
spec:
  template:
    spec:
      containers:
      - name: prometheus
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: chattingo-monitoring
spec:
  template:
    spec:
      containers:
      - name: grafana
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-uploader
  namespace: chattingo
spec:
  template:
    spec:
      containers:
      - name: s3-uploader
        image: adityagaikwad888/chattingo-s3-uploader:v1.0.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
  namespace: chattingo
spec:
  template:
    spec:
      containers:
      - name: log-processor
        image: adityagaikwad888/chattingo-log-processor:v1.0.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
